{
    "basics": {
      "name": "kushal c ",
      "label": "JRE",
      "email": "KUSHAL@GAMIL.com",
      "phone": "4 456-7890",
      "website": "https://johndoe.com",
      "summary": "A passionate and skilled CLERK .",
      "location": {
        "address": "123 Main Street",
        "postalCode": "12345",
        "city": "PDKT",
        "countryCode": "IND",
        "region": "INDIA"
      },
      "profiles": [
        {
          "network": "LinkedIn",
          "username": "KUSHI",
          "url": "https://www.linkedin.com/in/KUSHI"
        },
        {
          "network": "GitHub",
          "username": "SAALAI KUSHAL",
          "url": "https://github.com/KUSHI"
        }
      ]
    },
    "work": [
      {
        "company": "MUTHOOT Inc.",
        "position": "JRE",
        "website": "https://abc.com",
        "startDate": "2020-01-01",
        "endDate": "",
        
     
    
  }

  * window is the execution context and global object for that context's JavaScript
  
  * document contains the DOM, initialized by parsing HTML
  
  * screen describes the physical display's full screen